FAQ = [
("hola", "¡Hola! Bienvenido a ElectroWord."),
("que es electroword", "ElectroWord es una tienda de electrónica y tecnología."),
("donde estan las tiendas", "Puedes consultar nuestras tiendas en la web."),
("horario de atencion", "Abrimos de lunes a viernes de 9:00 a 20:00."),
("como seguir mi pedido", "Entra en 'Mi cuenta' > 'Pedidos' para ver el seguimiento."),
("cuanto tarda el envio", "El envío tarda entre 24 y 72 horas."),
("como devolver un producto", "Tienes 30 días para devolver desde 'Mi cuenta'."),
("metodos de pago", "Aceptamos tarjeta, PayPal y transferencia."),
("garantia", "Todos los productos tienen 3 años de garantía legal."),
("adios", "¡Hasta luego! Gracias por visitar ElectroWord."),
("como contactar soporte", "Puedes contactar soporte por email o chat en la web."),
("ofertas actuales", "Consulta nuestras ofertas actuales en la sección 'Promociones'."),
("envio internacional", "Sí, realizamos envíos internacionales con tarifas especiales."),
("cambiar contraseña", "Ve a 'Mi cuenta' > 'Configuración' para cambiar tu contraseña."),
("registrarse", "Puedes registrarte haciendo clic en 'Crear cuenta' en la web."),
("cancelar pedido", "Para cancelar un pedido, entra en 'Mis pedidos' y selecciona cancelar.") ,
("tarjeta regalo", "Disponemos de tarjetas regalo que se pueden comprar online."),
("politica devoluciones", "Consulta nuestra política de devoluciones en la sección legal."),
("estado pedido", "En 'Mis pedidos' puedes ver el estado de tu pedido en tiempo real."),
("soporte tecnico", "Nuestro soporte técnico está disponible de lunes a viernes de 9:00 a 18:00."),
]
